Update survey form
calvnce/surveyform pull request #1
Opened 2021-06-02 18:47 UTC by calvnce

2021-06-02 19:03 UTC, calvnce commented
Congratulations are in order for me and the previous colleague.

- The following are some of the notable adjustments identified and corrected:
- The elements should have unique IDs
- The for attribute of the Label tags should reference an existing ID
- CSS should be externally linked
- READ-ME File should be descriptive

NOTE: Since this is a review, I left the README file unchanged. So, as a reviewer, you may take this into account.

2021-06-03 00:53 UTC, Spayco requested changes
Hi @calvnce, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

Your review could use some improvements, please create a new one and double-check that you're following this list:
- GitHub features
  - it's best to utilize the "Review changes" feature from GitHub
  - (from the lesson page) it's required to find at least 2 issues in the code
  - please include those changes using [inline comments](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)
- Communication: 
  - kindly phrase the comments politely, as suggestions instead of orders. For example:
     * This is a polite suggestion: *"I think it would be better to use semantic tags"*
     * This reads as an order: *"Use semantic tags"*
  - please always include an explanation, a "why", for each requested change. For example:
     * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
     * This request lacks a "why": *Why don't you use an article tag here instead of a div?*
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 00:54 UTC, Spayco commented
> NOTE: Since this is a review, I left the README file unchanged. So, as a reviewer, you may take this into account. I know that it should be descriptive enough.

don't worry, this project focuses on the review only 😄

2021-06-03 14:19 UTC, calvnce reviewed
Congratulations for your efforts so far. However, just a coulee of head starts to add to the best practices:

- It is advisable to use a non-whites paced names as element IDs (eg. username, rather than "user name")
- It is good practice to make use of the external css - separate the styling from the HTML files
- More than often consider making good use of the style and semantic tags - this practice will make the code more readable and easy to maintain

2021-06-03 14:19 UTC, calvnce commented on index.html
> -      <form action="" id="survey-form">
The structure of the form tag is correct, however, I recommend the following changes:

- It is advisable not to include an empty string as an action place-holder
- If the form doesn't submit anything at all, then it would be just enough to ignore the action property.

2021-06-03 14:19 UTC, calvnce commented on index.html
> -        <label for="role">Which option best describes your current role?</label>
Correct use of Label tag, however, the following are considered good practice:

- The "for" property of the label tag is supposed to reference an existing HTML element 
- The "for property may reference only one element. It is a good practice to should always refrain from using the same ID for more than one "for" 
-

2021-06-03 14:23 UTC, calvnce commented
Thank you for the prompt feedback.

- The suggested adjustments are are now fully covered

2021-06-03 14:27 UTC, christianotieno approved these changes
Hi @calvnce, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 14:39 UTC, merged